### ISSUE TITLE
Upgrade plugin to work with 2.2.6

### ISSUE THREAD

**Issue by tsukasa1989** [sashas777/bug-from-email#6]
How to update this plugin to work on 2.2.6 which still has the issue looking at the ticket: https://github.com/magento/magento2/issues/14952

Would like to upgrade my Magento to 2.2.6 with this extension.

**Comment by KM-HM** [comment]
You could try to install the files manually, the composer settings of this modul do not allow composer to install this module in Magento 2.2.6. 
A limitation that was introduced in the hopes that Magento Team would fix this bug in the next patch.

**Comment by djamps** [comment]
FYI - After removing bug-from-email and upgrading to 2.2.6, it appears the issue may be finally resolved.   We are seeing the correct "FROM" address without the bug-from-email module.

**Comment by sashas777** [comment]
@tsukasa1989 @kemexyz @djamps 

So should I update to 2.2.6 or it is fixed there?

**Comment by djamps** [comment]
@sashas777 I am not seeing any more email issues on 2.2.6 both for orders and contact form, but I haven't tested every function yet.

**Comment by matthew99** [comment]
I had this installed on 2.2.4 and 2.2.5, and removed your plugin in order to update to 2.2.6. 
However, the bug is still there: no sender (FROM) in transactional email - at least not in the copies sent.
See also https://github.com/magento/magento2/issues/14952 there's a few others.
I am using Magical SMTP extension as well - their testmails do arrive with FROM
So it may be a great idea to update the plugin to work with 2.2.6

**Comment by sashas777** [comment]
@matthew99  Okay, I going to update it for 2.2.6
Thanks for the feedback
